library(RVAideMemoire)
library(MASS)

party_table <- matrix(c(192, 75, 8, 459, 586, 471), 2, byrow=T)
print(party_table)
chisq.test(party_table)
G.test(party_table)

print(head(Traffic))
print(nrow(Traffic))
print(mean(Traffic$y))
print(mean(Traffic$y[Traffic$year == 1961]))
print(mean(Traffic$y[Traffic$year == 1962]))
plot(Traffic$year, Traffic$y, main="Accidents by year")
print(mean(Traffic$y[Traffic$limit == "no"]))
print(mean(Traffic$y[Traffic$limit == "yes"]))
plot(Traffic$limit, Traffic$y, main="Accidents by speed limit presence")
plot(Traffic$y[Traffic$limit == "no"], main="Accidents with no speed limit")
plot(Traffic$y[Traffic$limit == "yes"], main="Accidents with speed limit")
plot(Traffic$day, Traffic$y, main="Accidents by day")

traffic_1961 <- subset(Traffic, year == 1961)
chisq.test(traffic_1961[c('day', 'y')])
traffic_1962 <- subset(Traffic, year == 1962)
chisq.test(traffic_1962[c('day', 'y')])
chisq.test(Traffic[c('day', 'y')])
print(summary(glm(y ~ limit, family="poisson", data=Traffic)))